bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: aft_mapped_to_init
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
    # - find_safe_goal_bt_node
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_wait_action_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_recovery_node_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

# controller_server:
#   ros__parameters:
#     use_sim_time: False
#     controller_frequency: 5.0
#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.001
#     min_theta_velocity_threshold: 0.001
#     failure_tolerance: 0.3
#     progress_checker_plugin: "progress_checker"
#     goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
#     controller_plugins: ["FollowPath"]

#     # Progress checker parameters
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
#       movement_time_allowance: 10.0

#     # Goal checker parameters
#     general_goal_checker:
#       stateful: True
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.05
#       yaw_goal_tolerance: 0.5
#     # DWB parameters
#     FollowPath:
#       plugin: "dwb_core::DWBLocalPlanner"
#       debug_trajectory_details: False
#       min_vel_x: -2.5
#       min_vel_y: -2.5
#       max_vel_x: 2.5
#       max_vel_y: 2.5
#       max_vel_theta: 12.0
#       min_speed_xy: -8.0
#       max_speed_xy: 8.0
#       min_speed_theta: -12.0
#       acc_lim_x: 5.0
#       acc_lim_y: 5.0
#       acc_lim_theta: 15.0
#       decel_lim_x: -5.0
#       decel_lim_y: -5.0
#       decel_lim_theta: -15.0
#       vx_samples: 20
#       vy_samples: 20
#       vtheta_samples: 20
#       sim_time: 0.51
#       linear_granularity: 0.05
#       angular_granularity: 0.025
#       transform_tolerance: 0.2
#       xy_goal_tolerance: 0.05
#       trans_stopped_velocity: 0.25
#       short_circuit_trajectory_evaluation: True
#       stateful: True
#       critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
#       BaseObstacle.scale: 0.02
#       PathAlign.scale: 8.0
#       PathAlign.forward_point_distance: 0.1
#       GoalAlign.scale: 6.0
#       GoalAlign.forward_point_distance: 0.1
#       PathDist.scale: 32.0
#       GoalDist.scale: 24.0
#       RotateToGoal.scale: 4.0
#       RotateToGoal.slowing_factor: 5.0
#       RotateToGoal.lookahead_time: -1.0
controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.5

    # Regulated Pure Pursuit Controller parameters
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      lookahead_time: 1.5
      regulated_linear_scaling_min_radius: 0.9
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_angular_vel_scaling: false
      use_cost_regulated_linear_velocity_scaling: false
      allow_reversing: false
      use_rotate_to_heading: true
      rotate_to_heading_min_angle: 0.785
      max_angular_vel: 1.0
      max_robot_pose_search_dist: 10.0
      use_interpolation: true

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 20.0
      publish_frequency: 10.0
      global_frame: odom
      # global_frame: camera_init
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      robot_radius: 0.2
      plugins: ["voxel2d_layer", "voxel3d_layer", "click_obstacles_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0
        inflation_radius: 0.7
      voxel2d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan 
        scan:
          topic: /scan
          raytrace_min_range: 0.0
          raytrace_max_range: 50.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel3d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: False
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        mark_threshold: 1
        observation_sources: livox
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0 
        livox:
          topic: /cloud_registerd
          raytrace_min_range: 0.0
          raytrace_max_range: 5.0
          min_obstacle_height: 0.2
          max_obstacle_height: 1.0 
          clearing: True
          marking: True
          data_type: "PointCloud2"
      click_obstacles_layer:
        plugin: "click_obstacles_layer::ClickObstaclesLayer"
        enabled: False
        obstacle_radius: 0.20
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 20.0
      publish_frequency: 10.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.2
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "voxel2d_layer", "voxel3d_layer", "click_obstacles_layer", "inflation_layer"]
      voxel2d_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud
        scan:
          topic: /scan
          raytrace_min_range: 0.0
          raytrace_max_range: 50.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        pointcloud:
          topic: /cloud_registered  # 您的点云话题名称
          data_type: "PointCloud2" # 关键：数据类型设置为点云
          marking: True
          clearing: True
          min_obstacle_height: 0.1  # 障碍物最小高度 (米)，用于过滤地面点
          max_obstacle_height: 1.0  # 障碍物最大高度 (米)，用于过滤过高的点
          obstacle_max_range: 5.0   # 标记为障碍物的最大距离
          obstacle_min_range: 0.5   # 标记为障碍物的最小距离
          raytrace_max_range: 5.5   # 清除障碍物的最大距离 (通常略大于 obstacle_max_range)
          raytrace_min_range: 0.0   # 清除障碍物的最小距离
      voxel3d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: False
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        mark_threshold: 1
        observation_sources: livox
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0 
        livox:
          topic: /cloud_registerd
          raytrace_min_range: 0.0
          raytrace_max_range: 50.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0 
          clearing: True
          marking: True
          data_type: "PointCloud2"
      click_obstacles_layer:
        plugin: "click_obstacles_layer::ClickObstaclesLayer"
        enabled: True
        obstacle_radius: 0.20
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0
        inflation_radius: 0.7
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      # plugin: "nav2_navfn_planner/NavfnPlanner"
      plugin: "nav2_smac_planner/SmacPlanner2D"
      # plugin: "nav2_theta_star_planner/ThetaStarPlanner"
      tolerance: 1.0
      allow_unknown: true
      downsample_costmap: false  # 地图很大时可设 true
      downsampling_factor: 2     # 下采样倍率（例如 5cm→10cm）
      cost_travel_multiplier: 2.0
      use_final_approach_orientation: true
      smoother:
        max_iterations: 200
        w_smooth: 0.8          # ↑ 从 0.3 提高，路径更直
        w_data: 0.2           # ↓ 从 0.2 降低，更少“贴原路径”
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 1

# planner_server_rclcpp_node:
#   ros__parameters:
#     use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    # global_frame: camera_init
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 20.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 10.0

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

# velocity_smoother:
#   ros__parameters:
#     use_sim_time: True
#     smoothing_frequency: 5.0
#     scale_velocities: False
#     feedback: "CLOSED_LOOP"
#     max_velocity: [2.5, 2.5, 12.0]
#     min_velocity: [-2.5, -2.5, -12.0]
#     max_accel: [5.0, 5.0, 15.0]
#     max_decel: [-5.0, -5.0, -15.0]
#     odom_topic: "aft_mapped_to_init"
#     odom_duration: 0.1
#     deadband_velocity: [0.0, 0.0, 0.0]
#     velocity_timeout: 1.0